POST http://localhost:3333/courses
Content-Type: application/json

{
      "title": "Curso de Fastify"
}

###

GET http://localhost:3333/courses

###

GET  http://localhost:3333/courses/6cae4f42-f854-4b5f-bc63-74d9590d8663